import type { Metadata } from "next";
import { Button, ButtonLink } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import typeScale from "@/styles/type-scale.generated.json";
import {
  checkContrast,
  loadInputs,
  passes,
} from "../../../../scripts/contrast.mjs";

export const metadata: Metadata = {
  title: "Style guide",
  robots: { index: false, follow: false },
};

const weights = [100, 200, 300, 400, 500, 600, 700, 800, 900];

const roles = [
  { name: "background", note: "page canvas" },
  { name: "surface", note: "cards, inputs, placeholders" },
  { name: "surface-raised", note: "nav pill, menus" },
  { name: "surface-sunken", note: "section bands, footer" },
  { name: "foreground", note: "text, solid ink fills" },
  { name: "muted", note: "secondary text" },
  { name: "subtle", note: "third-tier text, photo labels" },
  { name: "scrim", note: "fill behind text on photos" },
  { name: "veil", note: "dims the page behind dialogs" },
  { name: "outline", note: "interactive borders" },
  { name: "border", note: "container edges" },
  { name: "line", note: "dividers" },
  { name: "hover", note: "hover fill" },
  { name: "accent", note: "fills: buttons, badges" },
  { name: "accent-foreground", note: "text on accent" },
  { name: "accent-hover", note: "accent fill, hovered" },
  { name: "accent-edge", note: "border around an accent fill" },
  { name: "accent-text", note: "accent as readable text" },
  { name: "accent-soft", note: "tinted backgrounds" },
  { name: "highlight", note: "gold marks: underlines, states" },
  { name: "highlight-foreground", note: "text on highlight" },
  { name: "highlight-text", note: "gold as readable text" },
  { name: "error", note: "invalid borders, alert edges" },
  { name: "error-text", note: "error messages" },
  { name: "error-soft", note: "alert background" },
  { name: "focus", note: "focus ring" },
] as const;

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section aria-labelledby={`${id}-heading`} className="sg-section">
      <h2 id={`${id}-heading`}>{title}</h2>
      {children}
    </section>
  );
}

function Label({ children }: { children: React.ReactNode }) {
  return <p className="small muted">{children}</p>;
}

type Pairing = ReturnType<typeof checkContrast>[number];

// Never color alone: a miss is spelled out in the cell.
function ratio(row: Pairing, mode: "light" | "dark") {
  const value = row[mode];
  if (value === null) return "role missing";
  return passes(row, mode) ? `${value}:1` : `${value}:1, below minimum`;
}

export default async function StyleGuidePage() {
  const { config, steps, space } = typeScale;
  const { rolesCss, ramps } = await loadInputs();
  const pairs = checkContrast(rolesCss, ramps);

  return (
    <div className="stack stack--xl">
      <header className="stack">
        <h1 className="display">Style guide</h1>
        <p className="lead muted measure">
          A working reference for type, color and UI. Placeholder styles until
          the brand is settled. Not indexed.
        </p>
      </header>

      <Section id="typography" title="Typography">
        <div className="sg-split">
          <div className="stack stack--sm">
            <Label>Display: Cosmic (headings)</Label>
            <p className="display">El Camino Tattoos</p>
          </div>
          <div className="stack stack--sm">
            <Label>Body: Hanken Grotesk</Label>
            <p className="display sg-face-body">El Camino Tattoos</p>
          </div>
        </div>

        <div className="stack">
          <Label>
            Fluid scale: {config.minBase}px at {config.minViewport}px, ratio{" "}
            {config.minRatio} &rarr; {config.maxBase}px at {config.maxViewport}
            px, ratio {config.maxRatio}. Steps below base hold a fixed{" "}
            {config.smallRatio} ratio. Resize the window to watch it move.
            Generated by <code>pnpm type-scale</code>.
          </Label>
          {steps.map((step) => (
            <div key={step.name} className="sg-scale-row">
              <span className="small muted">
                text-{step.name} &middot; {step.minPx.toFixed(1)} &rarr;{" "}
                {step.maxPx.toFixed(1)}px
              </span>
              <span
                className="sg-face-display"
                style={{
                  fontSize: `var(--text-${step.name})`,
                  lineHeight: `var(--text-${step.name}--line-height)`,
                  letterSpacing: step.tracking ?? undefined,
                }}
              >
                Custom work, walk-ins, flash
              </span>
            </div>
          ))}
        </div>

        <div className="stack">
          <Label>Semantic classes</Label>
          <p className="display">.display</p>
          <h1>h1 / .heading-1</h1>
          <h2>h2 / .heading-2</h2>
          <h3>h3 / .heading-3</h3>
          <h4>h4 / .heading-4</h4>
          <p className="lead">.lead: introductory copy that sets up a page.</p>
          <p>Body: the default paragraph style.</p>
          <p className="small">.small: secondary detail.</p>
          <p className="caption">.caption: metadata and captions.</p>
          <p className="eyebrow">.eyebrow</p>
        </div>

        <div className="sg-split">
          <div className="stack stack--sm">
            <Label>Cosmic weights (variable, 100 to 900)</Label>
            {weights.map((weight) => (
              <p
                key={weight}
                className="heading-3"
                style={{ fontWeight: weight }}
              >
                {weight} Fine line, blackwork, traditional
              </p>
            ))}
          </div>
          <div className="stack stack--sm">
            <Label>Hanken Grotesk weights (variable, 100 to 900)</Label>
            {weights.map((weight) => (
              <p
                key={weight}
                className="heading-3 sg-face-body"
                style={{ fontWeight: weight }}
              >
                {weight} Fine line, blackwork, traditional
              </p>
            ))}
          </div>
        </div>

        <div className="stack measure">
          <Label>Body copy</Label>
          <p>
            Keep new tattoos clean and moisturized. Wash gently with
            fragrance-free soap, pat dry, and apply a thin layer of ointment.
            Avoid soaking, direct sun and picking at scabs while it heals.
          </p>
          <p className="small muted">
            Secondary text, captions and metadata use the muted color.
          </p>
          <p>
            A{" "}
            <a href="#typography" className="link">
              text link
            </a>{" "}
            sits inline with body copy.
          </p>
        </div>
      </Section>

      <Section id="spacing" title="Spacing">
        <div className="stack">
          <Label>
            Fluid space scale: multiples of the base size, so space and type
            scale together. Use these through Tailwind, e.g.{" "}
            <code>gap-fluid-md</code>, <code>p-fluid-lg</code>,{" "}
            <code>py-fluid-xl</code>. Generated by <code>pnpm type-scale</code>.
          </Label>
          {space.map((step) => (
            <div key={step.name} className="sg-scale-row">
              <span className="small muted">
                {step.name} &middot; {step.minPx.toFixed(1)} &rarr;{" "}
                {step.maxPx.toFixed(1)}px
              </span>
              <span
                className="sg-space-bar"
                style={{ inlineSize: `var(--spacing-fluid-${step.name})` }}
              />
            </div>
          ))}
        </div>
      </Section>

      <Section id="color" title="Color">
        <div className="stack">
          <Label>
            Roles, live in the current light or dark theme. Components use
            roles, never ramp steps directly.
          </Label>
          <ul className="sg-swatches">
            {roles.map(({ name, note }) => (
              <li key={name} className="stack stack--sm">
                <div
                  className="sg-swatch"
                  style={{ backgroundColor: `var(--${name})` }}
                />
                <p className="small">{name}</p>
                <p className="caption">{note}</p>
              </li>
            ))}
          </ul>
        </div>

        <div className="stack">
          <Label>
            Primitive ramps: brand colors pinned to steps, the rest generated in
            OKLCH. Edit the pinned values in scripts/color-ramps.mjs, then run{" "}
            <code>pnpm color-ramps</code>. Roles are hand-edited in{" "}
            <code>src/styles/roles.css</code>, no build step.
          </Label>
          {Object.entries(ramps as Record<string, Record<string, string>>).map(
            ([name, ramp]) => (
              <div key={name} className="stack stack--sm">
                <p className="small">{name}</p>
                <ul className="sg-ramp">
                  {Object.entries(ramp).map(([step, hex]) => (
                    <li key={step}>
                      <div
                        className="sg-swatch"
                        style={{ backgroundColor: hex }}
                      />
                      <p className="caption">{step}</p>
                      <p className="caption">{hex}</p>
                    </li>
                  ))}
                </ul>
              </div>
            ),
          )}
        </div>

        <table className="sg-table">
          <caption>
            Contrast, measured from roles.css. This only reports; run{" "}
            <code>pnpm check:contrast</code> to fail on a miss (CI does).
          </caption>
          <thead>
            <tr>
              <th scope="col">Pairing</th>
              <th scope="col">Used for</th>
              <th scope="col">Min</th>
              <th scope="col">Light</th>
              <th scope="col">Dark</th>
            </tr>
          </thead>
          <tbody>
            {pairs.map((pair) => (
              <tr key={`${pair.fg}-${pair.bg}`}>
                <th scope="row">
                  {pair.fg} on {pair.bg}
                </th>
                <td>{pair.note}</td>
                <td>{pair.min}:1</td>
                <td>{ratio(pair, "light")}</td>
                <td>{ratio(pair, "dark")}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section id="buttons" title="Buttons">
        <div className="cluster">
          <Button>Primary</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="ink">Ink</Button>
          <Button variant="ghost">Ghost</Button>
        </div>
        <div className="cluster">
          <Button disabled>Primary disabled</Button>
          <Button variant="secondary" disabled>
            Secondary disabled
          </Button>
          <Button variant="ink" disabled>
            Ink disabled
          </Button>
          <Button variant="ghost" disabled>
            Ghost disabled
          </Button>
          <Button pending>Pending</Button>
        </div>
        <div className="cluster">
          <Button size="sm">Small</Button>
          <Button size="md">Medium</Button>
          <Button size="lg">Large</Button>
        </div>
        <div className="cluster">
          <ButtonLink href="/contact">Link styled as button</ButtonLink>
          <ButtonLink href="/portfolio" variant="secondary">
            View portfolio
          </ButtonLink>
        </div>
      </Section>

      <Section id="forms" title="Form fields">
        <form className="sg-form" noValidate>
          <Field id="sg-name" label="Name">
            {(control) => (
              <input
                {...control}
                name="name"
                type="text"
                placeholder="Your name"
              />
            )}
          </Field>
          <Field
            id="sg-email"
            label="Email"
            hint="Where we reply. We don't share it."
            error="Enter an email address like name@example.com."
          >
            {(control) => (
              <input
                {...control}
                name="email"
                type="email"
                defaultValue="not-an-email"
              />
            )}
          </Field>
          <Field id="sg-artist" label="Artist">
            {(control) => (
              <select {...control} name="artist">
                <option>No preference</option>
                <option>Artist one</option>
                <option>Artist two</option>
              </select>
            )}
          </Field>
          <Field id="sg-idea" label="Tell us about your idea">
            {(control) => <textarea {...control} name="idea" rows={4} />}
          </Field>
          <fieldset className="fieldset">
            <legend className="field__label">Checked and unchecked</legend>
            <label className="check">
              <input type="checkbox" name="first-tattoo" defaultChecked />
              <span>This is my first tattoo</span>
            </label>
            <label className="check">
              <input type="checkbox" name="cover-up" />
              <span>This covers up an existing tattoo</span>
            </label>
            <label className="check">
              <input type="radio" name="sg-color" defaultChecked />
              <span>Black and gray</span>
            </label>
            <label className="check">
              <input type="radio" name="sg-color" />
              <span>Color</span>
            </label>
          </fieldset>
          <p className="form-status">
            <strong>Something went wrong.</strong> We couldn&rsquo;t send your
            message. Please try again in a moment.
          </p>
          <Button type="submit">Send</Button>
        </form>
      </Section>

      <Section id="filters" title="Filter chips">
        <ul className="filter-list">
          {["All", "Artist one", "Artist two", "Artist three"].map(
            (label, index) => (
              <li key={label}>
                <span
                  className="filter-chip"
                  aria-current={index === 0 ? "page" : undefined}
                >
                  {label}
                </span>
              </li>
            ),
          )}
        </ul>
      </Section>

      <Section id="richtext" title="Rich text">
        <div className="richtext measure">
          <p>
            Text an editor writes in Keystatic: paragraphs with{" "}
            <strong>bold</strong>, <em>italic</em> and{" "}
            <a href="#richtext-heading">links</a>.
          </p>
          <h3>Headings, lists</h3>
          <ul>
            <li>Bulleted items</li>
            <li>Keep each one short</li>
          </ul>
          <ol>
            <li>Numbered steps</li>
            <li>Read in order</li>
          </ol>
        </div>
      </Section>

      <Section id="cards" title="Cards and grid">
        <div className="sg-gallery">
          {Array.from({ length: 4 }, (_, index) => (
            <div key={index} className="sg-tile sg-tile--piece">
              4:5 piece tile
            </div>
          ))}
        </div>
        <div className="artist-grid">
          {["Artist one", "Artist two", "Artist three"].map((name) => (
            <div key={name}>
              <div className="sg-tile sg-tile--portrait">3:4 portrait</div>
              <h3 className="artist-card__name">{name}</h3>
              <p className="artist-card__meta">Fine line, Traditional</p>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}
