import type { Metadata } from "next";
import { Button, ButtonLink } from "@/components/ui/button";
import palette from "@/styles/palette.generated.json";
import typeScale from "@/styles/type-scale.generated.json";

export const metadata: Metadata = {
  title: "Style guide",
  robots: { index: false, follow: false },
};

const weights = [100, 200, 300, 400, 500, 600, 700, 800, 900];

const roles = [
  { name: "background", note: "page canvas" },
  { name: "surface", note: "placeholders, footer" },
  { name: "foreground", note: "text, primary actions" },
  { name: "muted", note: "secondary text" },
  { name: "outline", note: "interactive borders" },
  { name: "line", note: "dividers" },
  { name: "hover", note: "hover fill" },
  { name: "accent", note: "fills: buttons, badges" },
  { name: "accent-foreground", note: "text on accent" },
  { name: "accent-text", note: "orange as text or links" },
  { name: "accent-soft", note: "tinted backgrounds" },
  { name: "focus", note: "focus ring" },
] as const;

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section aria-labelledby={`${id}-heading`} className="sg-section">
      <h2 id={`${id}-heading`}>{title}</h2>
      {children}
    </section>
  );
}

function Label({ children }: { children: React.ReactNode }) {
  return <p className="small muted">{children}</p>;
}

export default function StyleGuidePage() {
  const { config, steps, space } = typeScale;

  return (
    <div className="stack stack--xl">
      <header className="stack">
        <h1 className="display">Style guide</h1>
        <p className="lead muted measure">
          A working reference for type, color and UI. Placeholder styles until
          the brand is settled. Not indexed.
        </p>
      </header>

      <Section id="typography" title="Typography">
        <div className="sg-split">
          <div className="stack stack--sm">
            <Label>Display: Cosmic (headings)</Label>
            <p className="display">El Camino Tattoos</p>
          </div>
          <div className="stack stack--sm">
            <Label>Body: Hanken Grotesk</Label>
            <p className="display sg-face-body">El Camino Tattoos</p>
          </div>
        </div>

        <div className="stack">
          <Label>
            Fluid scale: {config.minBase}px at {config.minViewport}px, ratio{" "}
            {config.minRatio} &rarr; {config.maxBase}px at {config.maxViewport}
            px, ratio {config.maxRatio}. Steps below base hold a fixed{" "}
            {config.smallRatio} ratio. Resize the window to watch it move.
            Generated by <code>pnpm type-scale</code>.
          </Label>
          {steps.map((step) => (
            <div key={step.name} className="sg-scale-row">
              <span className="small muted">
                text-{step.name} &middot; {step.minPx.toFixed(1)} &rarr;{" "}
                {step.maxPx.toFixed(1)}px
              </span>
              <span
                className="sg-face-display"
                style={{
                  fontSize: `var(--text-${step.name})`,
                  lineHeight: `var(--text-${step.name}--line-height)`,
                  letterSpacing: step.tracking ?? undefined,
                }}
              >
                Custom work, walk-ins, flash
              </span>
            </div>
          ))}
        </div>

        <div className="stack">
          <Label>Semantic classes</Label>
          <p className="display">.display</p>
          <h1>h1 / .heading-1</h1>
          <h2>h2 / .heading-2</h2>
          <h3>h3 / .heading-3</h3>
          <h4>h4 / .heading-4</h4>
          <p className="lead">.lead: introductory copy that sets up a page.</p>
          <p>Body: the default paragraph style.</p>
          <p className="small">.small: secondary detail.</p>
          <p className="caption">.caption: metadata and captions.</p>
          <p className="eyebrow">.eyebrow</p>
        </div>

        <div className="sg-split">
          <div className="stack stack--sm">
            <Label>Cosmic weights (variable, 100 to 900)</Label>
            {weights.map((weight) => (
              <p
                key={weight}
                className="heading-3"
                style={{ fontWeight: weight }}
              >
                {weight} Fine line, blackwork, traditional
              </p>
            ))}
          </div>
          <div className="stack stack--sm">
            <Label>Hanken Grotesk weights (variable, 100 to 900)</Label>
            {weights.map((weight) => (
              <p
                key={weight}
                className="heading-3 sg-face-body"
                style={{ fontWeight: weight }}
              >
                {weight} Fine line, blackwork, traditional
              </p>
            ))}
          </div>
        </div>

        <div className="stack measure">
          <Label>Body copy</Label>
          <p>
            Keep new tattoos clean and moisturized. Wash gently with
            fragrance-free soap, pat dry, and apply a thin layer of ointment.
            Avoid soaking, direct sun and picking at scabs while it heals.
          </p>
          <p className="small muted">
            Secondary text, captions and metadata use the muted color.
          </p>
          <p>
            A{" "}
            <a href="#typography" className="link">
              text link
            </a>{" "}
            sits inline with body copy.
          </p>
        </div>
      </Section>

      <Section id="spacing" title="Spacing">
        <div className="stack">
          <Label>
            Fluid space scale: multiples of the base size, so space and type
            scale together. Use these through Tailwind, e.g. <code>gap-md</code>
            , <code>p-lg</code>, <code>py-xl</code>. Generated by{" "}
            <code>pnpm type-scale</code>.
          </Label>
          {space.map((step) => (
            <div key={step.name} className="sg-scale-row">
              <span className="small muted">
                {step.name} &middot; {step.minPx.toFixed(1)} &rarr;{" "}
                {step.maxPx.toFixed(1)}px
              </span>
              <span
                className="sg-space-bar"
                style={{ inlineSize: `var(--spacing-${step.name})` }}
              />
            </div>
          ))}
        </div>
      </Section>

      <Section id="color" title="Color">
        <div className="stack">
          <Label>
            Roles, live in the current light or dark theme. Components use
            roles, never ramp steps directly.
          </Label>
          <ul className="sg-swatches">
            {roles.map(({ name, note }) => (
              <li key={name} className="stack stack--sm">
                <div
                  className="sg-swatch"
                  style={{ backgroundColor: `var(--${name})` }}
                />
                <p className="small">{name}</p>
                <p className="caption">{note}</p>
              </li>
            ))}
          </ul>
        </div>

        <div className="stack">
          <Label>
            Ramps: brand colors pinned to a step, the rest generated in OKLCH.
            Edit the pinned values and role picks in scripts/color-ramps.mjs,
            then run <code>pnpm color-ramps</code>.
          </Label>
          {Object.entries(palette.ramps).map(([name, ramp]) => (
            <div key={name} className="stack stack--sm">
              <p className="small">{name}</p>
              <ul className="sg-ramp">
                {Object.entries(ramp).map(([step, hex]) => (
                  <li key={step}>
                    <div
                      className="sg-swatch"
                      style={{ backgroundColor: hex }}
                    />
                    <p className="caption">{step}</p>
                    <p className="caption">{hex}</p>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <table className="sg-table">
          <caption>
            Contrast, measured from the generated palette. The generator fails
            if any row drops below its minimum.
          </caption>
          <thead>
            <tr>
              <th scope="col">Pairing</th>
              <th scope="col">Used for</th>
              <th scope="col">Min</th>
              <th scope="col">Light</th>
              <th scope="col">Dark</th>
            </tr>
          </thead>
          <tbody>
            {palette.pairs.map((pair) => (
              <tr key={`${pair.fg}-${pair.bg}`}>
                <th scope="row">
                  {pair.fg} on {pair.bg}
                </th>
                <td>{pair.note}</td>
                <td>{pair.min}:1</td>
                <td>{pair.light}:1</td>
                <td>{pair.dark}:1</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section id="buttons" title="Buttons">
        <div className="cluster">
          <Button>Primary</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="accent">Accent</Button>
          <Button variant="ghost">Ghost</Button>
          <Button disabled>Disabled</Button>
        </div>
        <div className="cluster">
          <Button size="sm">Small</Button>
          <Button size="md">Medium</Button>
          <Button size="lg">Large</Button>
        </div>
        <div className="cluster">
          <ButtonLink href="/contact">Link styled as button</ButtonLink>
          <ButtonLink href="/portfolio" variant="secondary">
            View portfolio
          </ButtonLink>
        </div>
      </Section>

      <Section id="forms" title="Form fields">
        <form className="sg-form">
          <div className="field">
            <label htmlFor="sg-name" className="field__label">
              Name
            </label>
            <input
              id="sg-name"
              name="name"
              type="text"
              placeholder="Your name"
              className="field__control"
            />
          </div>
          <div className="field">
            <label htmlFor="sg-email" className="field__label">
              Email
            </label>
            <input
              id="sg-email"
              name="email"
              type="email"
              placeholder="you@example.com"
              className="field__control"
            />
          </div>
          <div className="field">
            <label htmlFor="sg-artist" className="field__label">
              Artist
            </label>
            <select id="sg-artist" name="artist" className="field__control">
              <option>No preference</option>
              <option>Artist one</option>
              <option>Artist two</option>
            </select>
          </div>
          <div className="field">
            <label htmlFor="sg-idea" className="field__label">
              Tell us about your idea
            </label>
            <textarea
              id="sg-idea"
              name="idea"
              rows={4}
              className="field__control"
            />
          </div>
          <label className="check">
            <input type="checkbox" name="first-tattoo" />
            <span>This is my first tattoo</span>
          </label>
          <Button type="submit">Send</Button>
        </form>
      </Section>

      <Section id="filters" title="Filter chips">
        <ul className="filter-list">
          {["All", "Artist one", "Artist two", "Artist three"].map(
            (label, index) => (
              <li key={label}>
                <span
                  className="filter-chip"
                  aria-current={index === 0 ? "page" : undefined}
                >
                  {label}
                </span>
              </li>
            ),
          )}
        </ul>
      </Section>

      <Section id="cards" title="Cards and grid">
        <div className="sg-gallery">
          {Array.from({ length: 4 }, (_, index) => (
            <div key={index} className="sg-tile sg-tile--piece">
              4:5 piece tile
            </div>
          ))}
        </div>
        <div className="artist-grid">
          {["Artist one", "Artist two", "Artist three"].map((name) => (
            <div key={name}>
              <div className="sg-tile sg-tile--portrait">3:4 portrait</div>
              <h3 className="artist-card__name">{name}</h3>
              <p className="artist-card__meta">Fine line, Traditional</p>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}
