// Fluid modular type scale and space scale. Single source of truth for every
// --text-* and --spacing-* token.
//
// Each step is interpolated between two viewport widths (Utopia method):
//   - positive type steps: minRatio at minViewport -> maxRatio at maxViewport
//   - negative type steps: a fixed gentle ratio, so small text never shrinks
//     as the viewport grows (a growing ratio would push `xs` below ~11px).
//   - space steps: multiples of the base size, so space and type scale together.
//
// Edit the config below, then run `pnpm type-scale`.
import { writeFile } from "node:fs/promises";

const config = {
  minViewport: 320,
  maxViewport: 1240,
  minBase: 16,
  maxBase: 18,
  minRatio: 1.2, // major third on phones
  maxRatio: 1.333, // perfect fourth on wide screens
  smallRatio: 1.125, // steps below base, both ends
  floorPx: 12, // 0.75rem: no type step is ever smaller than this
};

// name -> Tailwind utility (`text-<name>`), step -> distance from base.
const steps = [
  { name: "xs", step: -2, lineHeight: 1.5 },
  { name: "sm", step: -1, lineHeight: 1.5 },
  { name: "base", step: 0, lineHeight: 1.55 },
  { name: "lg", step: 1, lineHeight: 1.45 },
  { name: "xl", step: 2, lineHeight: 1.3 },
  { name: "2xl", step: 3, lineHeight: 1.2 },
  { name: "3xl", step: 4, lineHeight: 1.1, tracking: "-0.01em" },
  { name: "4xl", step: 5, lineHeight: 1.05, tracking: "-0.02em" },
  { name: "5xl", step: 6, lineHeight: 1, tracking: "-0.02em" },
  { name: "6xl", step: 7, lineHeight: 1, tracking: "-0.03em" },
];

// name -> Tailwind spacing utility (`p-fluid-md`, `gap-fluid-lg`, ...),
// multiplier of base. The `fluid-` prefix is required: Tailwind's width and
// size utilities (`max-w-md`, `w-xl`) look up the same t-shirt names, so a bare
// `--spacing-md` silently turns `max-w-md` into a ~27px width.
const space = [
  { name: "3xs", multiplier: 0.25 },
  { name: "2xs", multiplier: 0.5 },
  { name: "xs", multiplier: 0.75 },
  { name: "sm", multiplier: 1 },
  { name: "md", multiplier: 1.5 },
  { name: "lg", multiplier: 2 },
  { name: "xl", multiplier: 3 },
  { name: "2xl", multiplier: 4 },
  { name: "3xl", multiplier: 6 },
];

const round = (n) => Math.round(n * 10000) / 10000;
const rem = (px) => `${round(px / 16)}rem`;

// clamp() that interpolates linearly between the two viewport widths.
function fluid(minPx, maxPx) {
  const slope = (maxPx - minPx) / (config.maxViewport - config.minViewport);
  const intercept = minPx - slope * config.minViewport;
  return `clamp(${rem(minPx)}, ${rem(intercept)} + ${round(slope * 100)}vw, ${rem(maxPx)})`;
}

function sizeAt(step) {
  const minRatio = step < 0 ? config.smallRatio : config.minRatio;
  const maxRatio = step < 0 ? config.smallRatio : config.maxRatio;
  const minPx = Math.max(config.floorPx, config.minBase * minRatio ** step);
  const maxPx = Math.max(config.floorPx, config.maxBase * maxRatio ** step);
  return { minPx, maxPx, value: fluid(minPx, maxPx) };
}

const rows = steps.map((s) => ({ ...s, ...sizeAt(s.step) }));

const spaceRows = space.map((s) => {
  const minPx = config.minBase * s.multiplier;
  const maxPx = config.maxBase * s.multiplier;
  return { ...s, minPx, maxPx, value: fluid(minPx, maxPx) };
});

const range = `${config.minBase}px @ ${config.minViewport}px`;
const rangeMax = `${config.maxBase}px @ ${config.maxViewport}px`;

const css = [
  "/* Generated by scripts/type-scale.mjs. Do not edit; run `pnpm type-scale`. */",
  `/* ${range}, ratio ${config.minRatio} -> ${rangeMax}, ratio ${config.maxRatio} */`,
  "@theme static {",
  "  --text-*: initial;",
  ...rows.flatMap((r) => [
    `  --text-${r.name}: ${r.value};`,
    `  --text-${r.name}--line-height: ${r.lineHeight};`,
    ...(r.tracking
      ? [`  --text-${r.name}--letter-spacing: ${r.tracking};`]
      : []),
  ]),
  "}",
  "",
].join("\n");

const spaceCss = [
  "/* Generated by scripts/type-scale.mjs. Do not edit; run `pnpm type-scale`. */",
  `/* ${range} -> ${rangeMax}. Multiples of the base size. */`,
  "@theme static {",
  ...spaceRows.map((r) => `  --spacing-fluid-${r.name}: ${r.value};`),
  "}",
  "",
].join("\n");

const json = rows.map(({ name, step, lineHeight, tracking, minPx, maxPx }) => ({
  name,
  step,
  lineHeight,
  tracking: tracking ?? null,
  minPx: round(minPx),
  maxPx: round(maxPx),
}));

const spaceJson = spaceRows.map(({ name, multiplier, minPx, maxPx }) => ({
  name,
  multiplier,
  minPx: round(minPx),
  maxPx: round(maxPx),
}));

await writeFile("src/styles/type-scale.css", css);
await writeFile("src/styles/space-scale.css", spaceCss);
await writeFile(
  "src/styles/type-scale.generated.json",
  `${JSON.stringify({ config, steps: json, space: spaceJson }, null, 2)}\n`,
);
console.log(
  `type-scale: wrote ${rows.length} type steps, ${spaceRows.length} space steps.`,
);
