// Fluid modular type scale. Single source of truth for every --text-* token.
//
// Each step is interpolated between two viewport widths (Utopia method):
//   - positive steps: minRatio at minViewport -> maxRatio at maxViewport
//   - negative steps: a fixed gentle ratio, so small text never shrinks as the
//     viewport grows (a growing ratio would push `xs` below ~11px).
//
// Edit the config below, then run `npm run type-scale`.
import { writeFile } from "node:fs/promises";

const config = {
  minViewport: 320,
  maxViewport: 1240,
  minBase: 16,
  maxBase: 18,
  minRatio: 1.2, // major third on phones
  maxRatio: 1.333, // perfect fourth on wide screens
  smallRatio: 1.125, // steps below base, both ends
  floorPx: 12, // 0.75rem: no step is ever smaller than this
};

// name -> Tailwind utility (`text-<name>`), step -> distance from base.
const steps = [
  { name: "xs", step: -2, lineHeight: 1.5 },
  { name: "sm", step: -1, lineHeight: 1.5 },
  { name: "base", step: 0, lineHeight: 1.55 },
  { name: "lg", step: 1, lineHeight: 1.45 },
  { name: "xl", step: 2, lineHeight: 1.3 },
  { name: "2xl", step: 3, lineHeight: 1.2 },
  { name: "3xl", step: 4, lineHeight: 1.1, tracking: "-0.01em" },
  { name: "4xl", step: 5, lineHeight: 1.05, tracking: "-0.02em" },
  { name: "5xl", step: 6, lineHeight: 1, tracking: "-0.02em" },
  { name: "6xl", step: 7, lineHeight: 1, tracking: "-0.03em" },
];

const round = (n) => Math.round(n * 10000) / 10000;
const rem = (px) => `${round(px / 16)}rem`;

function sizeAt(step) {
  const minRatio = step < 0 ? config.smallRatio : config.minRatio;
  const maxRatio = step < 0 ? config.smallRatio : config.maxRatio;
  const minPx = Math.max(config.floorPx, config.minBase * minRatio ** step);
  const maxPx = Math.max(config.floorPx, config.maxBase * maxRatio ** step);
  const slope = (maxPx - minPx) / (config.maxViewport - config.minViewport);
  const intercept = minPx - slope * config.minViewport;
  const fluid = `${rem(intercept)} + ${round(slope * 100)}vw`;
  return {
    minPx,
    maxPx,
    value: `clamp(${rem(minPx)}, ${fluid}, ${rem(maxPx)})`,
  };
}

const rows = steps.map((s) => ({ ...s, ...sizeAt(s.step) }));

const css = [
  "/* Generated by scripts/type-scale.mjs. Do not edit; run `npm run type-scale`. */",
  `/* ${config.minBase}px @ ${config.minViewport}px, ratio ${config.minRatio} -> ${config.maxBase}px @ ${config.maxViewport}px, ratio ${config.maxRatio} */`,
  "@theme static {",
  "  --text-*: initial;",
  ...rows.flatMap((r) => [
    `  --text-${r.name}: ${r.value};`,
    `  --text-${r.name}--line-height: ${r.lineHeight};`,
    ...(r.tracking
      ? [`  --text-${r.name}--letter-spacing: ${r.tracking};`]
      : []),
  ]),
  "}",
  "",
].join("\n");

const json = rows.map(({ name, step, lineHeight, tracking, minPx, maxPx }) => ({
  name,
  step,
  lineHeight,
  tracking: tracking ?? null,
  minPx: round(minPx),
  maxPx: round(maxPx),
}));

await writeFile("src/styles/type-scale.css", css);
await writeFile(
  "src/styles/type-scale.generated.json",
  `${JSON.stringify({ config, steps: json }, null, 2)}\n`,
);
console.log(`type-scale: wrote ${rows.length} steps.`);
